NUMPY

In [48]:
import numpy as np

In [49]:
data1 = np.array([1, 2, 3])
print(data1)

[1 2 3]


In [50]:
data2 = np.array([[1, 2, 3], [4, 5, 7.0]])
print(data2)

[[1. 2. 3.]
 [4. 5. 7.]]


1. Queries about the array:
- shape
- size
- ndim
- nbytes
- dtype


In [51]:
print("Shape of data2:", data2.shape)
print("Size of data2:", data2.size)
print("Number of dimensions of data2:", data2.ndim)
print("Number of bytes used by data2:", data2.nbytes)
print("Data type of data2:", data2.dtype)

Shape of data2: (2, 3)
Size of data2: 6
Number of dimensions of data2: 2
Number of bytes used by data2: 48
Data type of data2: float64


Extracting rows and colums

In [52]:
n_r = data2.shape[0];
n_c = data2.shape[1];
print("Number of rows:", n_r)
print("Number of columns:", n_c)
print("Data type of data2:", data2.dtype)

Number of rows: 2
Number of columns: 3
Data type of data2: float64


Type casting

In [53]:
data = np.array([1,2,3], dtype=np.complex64)
print(data.dtype)
print(data)

complex64
[1.+0.j 2.+0.j 3.+0.j]


In [54]:
# Typecasting using astype method
data_int = np.array([1.0, 2.0, 3.0])
data_int = data_int.astype(np.int32)
print(data_int.dtype)
print(data_int)

int32
[1 2 3]


In [55]:
data=np.array([1,2,3])
data =data.astype(np.complex64)
print(data)

[1.+0.j 2.+0.j 3.+0.j]


2. Array initialization methods
- One should avoid dynamic arrays
- C -> malloc


In [56]:
#array initialisation
a=np.zeros([2,2,2])
print(a)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [57]:
# Creating a 5x5 identity matrix
c = np.eye(5) # or np.identity(5)
print(c)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Create a diagonal matrix

In [58]:
d=np.array([[1,2,3],[4,5,6],[7,8,9]])
#print(d)
e= np.diag(d)
print(e)
d1=np.array([1,2,3])
e1=np.diag(d1)
print(e1)
d2 = np.array([[1,2,3],[4,5,6]])
e2=np.diag(d2)
print(e2)

[1 5 9]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[1 5]


In [59]:
print(data1)
d = np.diag(data1)
print(d)

[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


Linspace and Logspace

In [60]:
e = np.linspace(1, 2, 11)
print(e)
f = np.logspace(2, 3, 11)
print(f)
print(f.shape)

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2. ]
[ 100.          125.89254118  158.48931925  199.5262315   251.18864315
  316.22776602  398.10717055  501.18723363  630.95734448  794.32823472
 1000.        ]
(11,)


In [61]:
g = lambda i,j: i*j

In [62]:
print(g(2,3))

6


- Printing the `data1` array and its diagonal matrix.
- Using `linspace` and `logspace` for creating arrays.
- Defining a lambda function.
- Testing the lambda function.

In [63]:
x1 = np.linspace(0,5,6)
y1 = np.linspace(0,10,11)

print(x1, y1)

[0. 1. 2. 3. 4. 5.] [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [64]:
x,y = np.meshgrid(x1,y1)
print(x)

[[0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]]


In [65]:
Z = np.cos(x) * np.sin(y)
print(Z)

[[ 0.          0.         -0.         -0.         -0.          0.        ]
 [ 0.84147098  0.45464871 -0.35017549 -0.83304996 -0.55002214  0.2386935 ]
 [ 0.90929743  0.4912955  -0.37840125 -0.90019763 -0.59435646  0.2579333 ]
 [ 0.14112001  0.07624747 -0.05872664 -0.13970775 -0.09224219  0.04003041]
 [-0.7568025  -0.40890213  0.31494096  0.74922879  0.49467912 -0.21467625]
 [-0.95892427 -0.518109    0.3990533   0.94932784  0.62679474 -0.27201056]
 [-0.2794155  -0.15096884  0.11627788  0.27661925  0.18263816 -0.07925961]
 [ 0.6569866   0.35497137 -0.27340289 -0.6504118  -0.4294351   0.18636225]
 [ 0.98935825  0.53455254 -0.4117183  -0.97945724 -0.64668771  0.28064352]
 [ 0.41211849  0.22266857 -0.1715018  -0.40799421 -0.26937862  0.11690243]
 [-0.54402111 -0.29393586  0.22639266  0.53857682  0.35559593 -0.15431822]]


In [66]:
# Creating and manipulating arrays x2 and y2
x2 = np.linspace(0, 5, 12)
y2 = x2.copy()  # Copy x2 to y2
print(x2)
print(y2)
y2[0] = -1  # Modify the first element of y2
print(y2)
print(x2)

[0.         0.45454545 0.90909091 1.36363636 1.81818182 2.27272727
 2.72727273 3.18181818 3.63636364 4.09090909 4.54545455 5.        ]
[0.         0.45454545 0.90909091 1.36363636 1.81818182 2.27272727
 2.72727273 3.18181818 3.63636364 4.09090909 4.54545455 5.        ]
[-1.          0.45454545  0.90909091  1.36363636  1.81818182  2.27272727
  2.72727273  3.18181818  3.63636364  4.09090909  4.54545455  5.        ]
[0.         0.45454545 0.90909091 1.36363636 1.81818182 2.27272727
 2.72727273 3.18181818 3.63636364 4.09090909 4.54545455 5.        ]


In [67]:

x3 = np.linspace(0, 6, 7)
y3 = x3  # Copy x2 to y2
print(x3)
print(y3)
y3[0] = -1 
print(y3)
print(x3)

[0. 1. 2. 3. 4. 5. 6.]
[0. 1. 2. 3. 4. 5. 6.]
[-1.  1.  2.  3.  4.  5.  6.]
[-1.  1.  2.  3.  4.  5.  6.]


In [68]:
# Creating an identity matrix and printing it
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


- Creating and manipulating arrays `x2` and `y2`.
- Creating and printing an identity matrix.


In [69]:
y3 = np.eye(len(x2))
print(y3)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [72]:
y3 = np.diag(np.ones(np.shape(x2)))
y3

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [70]:
x = np.linspace(0, 2 * np.pi, 20)
y = np.sin(x)
mask = y >= 0 # Create a boolean mask
print(y)
print(mask)
print(y[mask])


[ 0.00000000e+00  3.24699469e-01  6.14212713e-01  8.37166478e-01
  9.69400266e-01  9.96584493e-01  9.15773327e-01  7.35723911e-01
  4.75947393e-01  1.64594590e-01 -1.64594590e-01 -4.75947393e-01
 -7.35723911e-01 -9.15773327e-01 -9.96584493e-01 -9.69400266e-01
 -8.37166478e-01 -6.14212713e-01 -3.24699469e-01 -2.44929360e-16]
[ True  True  True  True  True  True  True  True  True  True False False
 False False False False False False False False]
[0.         0.32469947 0.61421271 0.83716648 0.96940027 0.99658449
 0.91577333 0.73572391 0.47594739 0.16459459]


In [73]:
A = np.sin(np.linspace(0, 2 * np.pi, 20))
print(A)
B = A[A > 0]
print(A >= 0)
print(B)

C = np.linspace(0, 1, 20)
D = C[A > 0]
print(C)
print(D)

[ 0.00000000e+00  3.24699469e-01  6.14212713e-01  8.37166478e-01
  9.69400266e-01  9.96584493e-01  9.15773327e-01  7.35723911e-01
  4.75947393e-01  1.64594590e-01 -1.64594590e-01 -4.75947393e-01
 -7.35723911e-01 -9.15773327e-01 -9.96584493e-01 -9.69400266e-01
 -8.37166478e-01 -6.14212713e-01 -3.24699469e-01 -2.44929360e-16]
[ True  True  True  True  True  True  True  True  True  True False False
 False False False False False False False False]
[0.32469947 0.61421271 0.83716648 0.96940027 0.99658449 0.91577333
 0.73572391 0.47594739 0.16459459]
[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]
[0.05263158 0.10526316 0.15789474 0.21052632 0.26315789 0.31578947
 0.36842105 0.42105263 0.47368421]


In [74]:
A = np.arange(10)
print(A)

indices = np.array([True, True, False, True, True,
                   True, False, True, False, False])
B = A[indices]  # not a view, it's a copy
B[0] = 20
print(B)
print(A)

[0 1 2 3 4 5 6 7 8 9]
[20  1  3  4  5  7]
[0 1 2 3 4 5 6 7 8 9]


In [76]:
a = np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [78]:
b = np.outer(a,a)
b

array([[100, 110, 120, 130, 140, 150, 160, 170, 180, 190],
       [110, 121, 132, 143, 154, 165, 176, 187, 198, 209],
       [120, 132, 144, 156, 168, 180, 192, 204, 216, 228],
       [130, 143, 156, 169, 182, 195, 208, 221, 234, 247],
       [140, 154, 168, 182, 196, 210, 224, 238, 252, 266],
       [150, 165, 180, 195, 210, 225, 240, 255, 270, 285],
       [160, 176, 192, 208, 224, 240, 256, 272, 288, 304],
       [170, 187, 204, 221, 238, 255, 272, 289, 306, 323],
       [180, 198, 216, 234, 252, 270, 288, 306, 324, 342],
       [190, 209, 228, 247, 266, 285, 304, 323, 342, 361]])

In [80]:
c=np.ravel(b) # flatten the array
c

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 110, 121, 132,
       143, 154, 165, 176, 187, 198, 209, 120, 132, 144, 156, 168, 180,
       192, 204, 216, 228, 130, 143, 156, 169, 182, 195, 208, 221, 234,
       247, 140, 154, 168, 182, 196, 210, 224, 238, 252, 266, 150, 165,
       180, 195, 210, 225, 240, 255, 270, 285, 160, 176, 192, 208, 224,
       240, 256, 272, 288, 304, 170, 187, 204, 221, 238, 255, 272, 289,
       306, 323, 180, 198, 216, 234, 252, 270, 288, 306, 324, 342, 190,
       209, 228, 247, 266, 285, 304, 323, 342, 361])