In [2]:
import numpy as np

In [3]:
a = np.zeros((3,3))
np.fill_diagonal(a,1)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
m1 = np.random.randint(10,50,(5,5))
print(m1)
m1[m1>30] = -1
m1

[[22 27 41 25 28]
 [29 39 19 20 33]
 [39 15 12 28 19]
 [11 22 28 23 18]
 [16 13 15 11 41]]


array([[22, 27, -1, 25, 28],
       [29, -1, 19, 20, -1],
       [-1, 15, 12, 28, 19],
       [11, 22, 28, 23, 18],
       [16, 13, 15, 11, -1]])

In [5]:
rm=np.random.rand(4,4)
print(rm)
a = np.argmax(rm)
print(a)
max_in=np.unravel_index(np.argmax(rm, axis=None), rm.shape)
print(max_in)

[[0.60949207 0.56842105 0.8493613  0.29416234]
 [0.65730753 0.5266533  0.3218953  0.28227947]
 [0.29158172 0.42947772 0.0094228  0.69875373]
 [0.94550471 0.54218775 0.09570916 0.00804712]]
12
(3, 0)


In [6]:
def transf(m):
    tm = np.array([[int(e/2) if e%2 == 0 else int(e**2) for e in row]for row in m])
    return tm


# print(transf(np.array([[4, 3, 6, 7],
#                        [2, 9, 8, 5],
#                        [10, 11, 14, 13],
#                        [12, 1, 16, 15]])))
print(transf(m1))
print(m1)

[[ 11 729   1 625  14]
 [841   1 361  10   1]
 [  1 225   6  14 361]
 [121  11  14 529   9]
 [  8 169 225 121   1]]
[[22 27 -1 25 28]
 [29 -1 19 20 -1]
 [-1 15 12 28 19]
 [11 22 28 23 18]
 [16 13 15 11 -1]]


In [7]:
l1 = np.linspace(0,100,20)
print(l1)

[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]


In [8]:
# Create a matrix where each element is the product of its row and column indices
def prod_matrix(n):
    return np.fromfunction(lambda i, j: i*j, (n, n), dtype=int)

In [16]:
#Create a 10x10 matrix where the elements on the boundary are 1 and all other elements are 0:
# a=np.zeros((10,10))
# a[0,:]=1
# a[-1,:]=1
# a[:,0]=1
# a[:,-1]=1
# a
matrix = np.ones((10,10))
matrix[1:-1,1:-1] = 0 # index from 1, but -1 th element wont be included only till -2
matrix

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [25]:
# Create two matrices of shape 3x3. Add them together only if their sum is greater than a threshold value of 10
m1 = np.random.randint(0,3,(3,3))
m2 = np.random.randint(0,3,(3,3))
print(m1)
print(m2)
threshold = 10
m3 = m1+m2
m3>threshold


[[0 0 1]
 [0 2 0]
 [0 0 1]]
[[0 0 2]
 [0 0 0]
 [1 0 2]]


array([[False, False, False],
       [False, False, False],
       [False, False, False]])